"..."

#: import dp kivy.metrics

<ScoreWidget>:
    canvas.before:
        Color:
            rgba: 1, 0, 0, 1
        Rectangle:
            size: self.size
    score: score
    best_score: best_score
    Label:
        text: " S  C  O  R  E " # + str(root.score)
        font_name: "fonts/Eurostile.ttf"
        font_size: dp(40)
        pos_hint: {"center_x": .5, "top": 1}
        size_hint: 1, .5
